// app/clientRouter.tsx
import { createRouter as createTanStackRouter } from "@tanstack/react-router";

import { ssr } from "@carvajalconsultants/headstart/client";
import { Provider } from "urql";

import { client } from "./graphql/clientProvider";
import { routeTree } from "./routeTree.gen";

import type { ReactNode } from "react";
import type { SSRData } from "urql";

export const createRouter = () => {
  const router = createTanStackRouter({
    routeTree,
    context: {
      client,
    },
    hydrate: (dehydrated) => {
      // Hydrate URQL with data passed by TSR, this is generated by dehydrate function in server router.
      ssr.restoreData(dehydrated.initialData as SSRData);
    },

    // Wrap our entire route with the URQL provider so we can execute queries and mutations.
    Wrap: ({ children }: { children: ReactNode }) => <Provider value={client}>{children}</Provider>,
  });

  return router;
};

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof createRouter>;
  }
}
